name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo 'All I want is love'
