name: Release

on:
  push:
    branches:
      - next
      - next-major
      - beta
      - alpha

  workflow_dispatch:

jobs:
  semantic:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_RELEASE: ${{ secrets.GH_TOKEN_RELEASE }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            semantic-github-pullrequest

      - name: New release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Store changelog file
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  package:
    needs: semantic
    runs-on: ubuntu-latest
    name: Package release
    if: needs.semantic.outputs.new_release_published == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: v${{ needs.semantic.outputs.new_release_version }}
      - name: Download changelog file
        uses: actions/download-artifact@v2
        with:
          name: changelog

      - name: Create package
        id: package
        run: ./package.sh 'v${{ needs.semantic.outputs.new_release_version }}'

      - name: Publish package
        run: |
          for f in '${{ steps.package.outputs.package }}'; do
            echo "Uploading release file '$f'..."
            gh release upload 'v${{ needs.semantic.outputs.new_release_version }}' "$f" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store package
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ${{ steps.package.outputs.package }}
